services:
  db:
    image: postgres:15
    env_file:
      - .env

  backend:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    image: nginx:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
